language: julia

os:
  - linux

julia:
  - 1.3

notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone("https://github.com/TsurHerman/Fezzik.git"); Pkg.build(Fezzik");'
  - julia -e 'Pkg.clone("https://github.com/mdpetters/AtmosphericThermodynamics.git"); Pkg.build("AtmosphericThermodynamics");'
  - julia -e 'Pkg.clone("https://github.com/mdpetters/DifferentialMobilityAnalyzers.jl.git"); Pkg.build("DifferentialMobilityAnalyzers");'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

