# This file is machine-generated - editing it directly is not advised

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Roots]]
deps = ["Printf"]
git-tree-sha1 = "dcc013908465ca1019b34b4bf547b6a187d195f9"
uuid = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
version = "0.8.4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
